# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\titleBarUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from Components.TitleBar.MovableLabel import MovableLabel


class UiTitleBarWidget(object):
    def setup_ui(self, titleBarWidget):
        titleBarWidget.setObjectName("titleBarWidget")
        titleBarWidget.resize(600, 40) # 600 40
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(titleBarWidget.sizePolicy().hasHeightForWidth())
        titleBarWidget.setSizePolicy(sizePolicy)
        titleBarWidget.setMinimumSize(QtCore.QSize(0, 40))
        titleBarWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.verticalLayout = QtWidgets.QVBoxLayout(titleBarWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleBarWidget_2 = QtWidgets.QWidget(titleBarWidget)
        self.titleBarWidget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.titleBarWidget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titleBarWidget_2.setStyleSheet("QWidget#titleBarWidget_2{\n"
                                            "    background-color:rgb(12, 11, 16);\n"
                                            "}")
        self.titleBarWidget_2.setObjectName("titleBarWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleBarWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleBarLabel_7 = MovableLabel(self.titleBarWidget_2)
        self.titleBarLabel_7.setMinimumSize(QtCore.QSize(25, 40))
        self.titleBarLabel_7.setMaximumSize(QtCore.QSize(25, 40))
        self.titleBarLabel_7.setText("")
        self.titleBarLabel_7.setObjectName("titleBarLabel_7")
        self.horizontalLayout_2.addWidget(self.titleBarLabel_7)
        self.titleBarWidget_5 = QtWidgets.QWidget(self.titleBarWidget_2)
        self.titleBarWidget_5.setMinimumSize(QtCore.QSize(0, 40))
        self.titleBarWidget_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titleBarWidget_5.setObjectName("titleBarWidget_5")
        # self.titleBarWidget_5.setStyleSheet("""
                                            # background-color: red;""")  # <---------
        # self.titleBarWidget_5.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                                                  # QtWidgets.QSizePolicy.Preferred))    # <---------
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.titleBarWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleBarLabel_6 = MovableLabel(self.titleBarWidget_5)
        self.titleBarLabel_6.setMinimumSize(QtCore.QSize(0, 5))
        self.titleBarLabel_6.setMaximumSize(QtCore.QSize(16777215, 5))
        self.titleBarLabel_6.setText("")
        self.titleBarLabel_6.setObjectName("titleBarLabel_6")
        self.verticalLayout_3.addWidget(self.titleBarLabel_6)
        self.titleBarWidget_6 = QtWidgets.QWidget(self.titleBarWidget_5)
        self.titleBarWidget_6.setObjectName("titleBarWidget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleBarWidget_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        # self.horizontalLayout.setAlignment(QtCore.Qt.AlignLeft)     # <----------------------
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3.addWidget(self.titleBarWidget_6)
        self.horizontalLayout_2.addWidget(self.titleBarWidget_5)
        self.titleBarLabel_5 = MovableLabel(self.titleBarWidget_2)
        self.titleBarLabel_5.setMinimumSize(QtCore.QSize(15, 40))
        self.titleBarLabel_5.setMaximumSize(QtCore.QSize(15, 40))
        self.titleBarLabel_5.setText("")
        self.titleBarLabel_5.setObjectName("titleBarLabel_5")
        self.horizontalLayout_2.addWidget(self.titleBarLabel_5)
        self.titleBarWidget_4 = QtWidgets.QWidget(self.titleBarWidget_2)
        self.titleBarWidget_4.setMinimumSize(QtCore.QSize(30, 40))
        self.titleBarWidget_4.setMaximumSize(QtCore.QSize(30, 40))
        self.titleBarWidget_4.setStyleSheet("QPushButton{\n"
                                            "    background-color:rgba(0, 0, 0, 0);\n"
                                            "    color:rgb(255, 255, 255);\n"
                                            "    font-size:17px;\n"
                                            "    font-family:dripicons-v2;\n"
                                            "    padding-top:3px;\n"
                                            "}\n"
                                            "QPushButton:hover{\n"
                                            "    background-color:rgba(144, 144, 144, 30);\n"
                                            "    border-radius:5px;\n"
                                            "}\n"
                                            "QPushButton:pressed{\n"
                                            "    padding-top:5px;\n"
                                            "    padding-left:5px;\n"
                                            "}")
        self.titleBarWidget_4.setObjectName("titleBarWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleBarWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleBarLabel_3 = MovableLabel(self.titleBarWidget_4)
        self.titleBarLabel_3.setMinimumSize(QtCore.QSize(0, 7))
        self.titleBarLabel_3.setMaximumSize(QtCore.QSize(16777215, 7))
        self.titleBarLabel_3.setText("")
        self.titleBarLabel_3.setObjectName("titleBarLabel_3")
        self.verticalLayout_2.addWidget(self.titleBarLabel_3)
        self.titleBarPushButton_4 = QtWidgets.QPushButton(self.titleBarWidget_4)
        self.titleBarPushButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton_4.setObjectName("titleBarPushButton_4")
        self.verticalLayout_2.addWidget(self.titleBarPushButton_4)
        self.titleBarLabel_4 = MovableLabel(self.titleBarWidget_4)
        self.titleBarLabel_4.setMinimumSize(QtCore.QSize(0, 3))
        self.titleBarLabel_4.setMaximumSize(QtCore.QSize(16777215, 3))
        self.titleBarLabel_4.setText("")
        self.titleBarLabel_4.setObjectName("titleBarLabel_4")
        self.verticalLayout_2.addWidget(self.titleBarLabel_4)
        self.horizontalLayout_2.addWidget(self.titleBarWidget_4)
        self.titleBarLabel_2 = MovableLabel(self.titleBarWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleBarLabel_2.sizePolicy().hasHeightForWidth())
        self.titleBarLabel_2.setSizePolicy(sizePolicy)
        self.titleBarLabel_2.setMinimumSize(QtCore.QSize(50, 40))
        self.titleBarLabel_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titleBarLabel_2.setText("")
        self.titleBarLabel_2.setObjectName("titleBarLabel_2")
        self.horizontalLayout_2.addWidget(self.titleBarLabel_2)
        self.titleBarWidget_3 = QtWidgets.QWidget(self.titleBarWidget_2)
        self.titleBarWidget_3.setMinimumSize(QtCore.QSize(90, 40))
        self.titleBarWidget_3.setMaximumSize(QtCore.QSize(90, 40))
        self.titleBarWidget_3.setStyleSheet("QPushButton{\n"
                                            "    background-color:rgba(0, 0, 0, 0);\n"
                                            "    color:rgb(255, 255, 255);\n"
                                            "    border-radius:1px;\n"
                                            "    font-size:18px;\n"
                                            "    font-family:dripicons-v2;\n"
                                            "}\n"
                                            "QPushButton:hover{\n"
                                            "    background-color:rgb(49, 48, 53);\n"
                                            "}\n"
                                            "QPushButton#titleBarPushButton:hover{\n"
                                            "    background-color:rgb(232, 17, 35);\n"
                                            "}\n"
                                            "QPushButton:pressed{\n"
                                            "    padding-top:5px;\n"
                                            "    padding-left:5px;\n"
                                            "}")
        self.titleBarWidget_3.setObjectName("titleBarWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.titleBarWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.titleBarPushButton_3 = QtWidgets.QPushButton(self.titleBarWidget_3)
        self.titleBarPushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton_3.setStyleSheet("")
        self.titleBarPushButton_3.setObjectName("titleBarPushButton_3")
        self.gridLayout.addWidget(self.titleBarPushButton_3, 0, 0, 1, 1)
        self.titleBarPushButton = QtWidgets.QPushButton(self.titleBarWidget_3)
        self.titleBarPushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton.setObjectName("titleBarPushButton")
        self.gridLayout.addWidget(self.titleBarPushButton, 0, 2, 1, 1)
        self.titleBarPushButton_2 = QtWidgets.QPushButton(self.titleBarWidget_3)
        self.titleBarPushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.titleBarPushButton_2.setStyleSheet("font-size:13px;")
        self.titleBarPushButton_2.setCheckable(True)
        self.titleBarPushButton_2.setObjectName("titleBarPushButton_2")
        self.gridLayout.addWidget(self.titleBarPushButton_2, 0, 1, 1, 1)
        self.titleBarLabel = MovableLabel(self.titleBarWidget_3)
        self.titleBarLabel.setMinimumSize(QtCore.QSize(0, 10))
        self.titleBarLabel.setMaximumSize(QtCore.QSize(16777215, 10))
        self.titleBarLabel.setText("")
        self.titleBarLabel.setObjectName("titleBarLabel")
        self.gridLayout.addWidget(self.titleBarLabel, 1, 0, 1, 3)
        self.horizontalLayout_2.addWidget(self.titleBarWidget_3)
        self.verticalLayout.addWidget(self.titleBarWidget_2)

        self.retranslate_ui(titleBarWidget)
        QtCore.QMetaObject.connectSlotsByName(titleBarWidget)

    def retranslate_ui(self, titleBarWidget):
        _translate = QtCore.QCoreApplication.translate
        titleBarWidget.setWindowTitle(_translate("titleBarWidget", "Form"))
        self.titleBarPushButton_4.setText(_translate("titleBarWidget", ""))
        self.titleBarPushButton_3.setText(_translate("titleBarWidget", ""))
        self.titleBarPushButton.setText(_translate("titleBarWidget", "9"))
        self.titleBarPushButton_2.setText(_translate("titleBarWidget", ""))
